### ISSUE TITLE
ENH: Ability to specify source address

### ISSUE THREAD

**Issue by olafayomi** [gufolabs/gufo_ping#3]
### Proposed new feature or change:

Hi,
It will be nice to have the ability to specify the source address of the ICMP packets for situations where there are multiple addresses available on the host. Is such a feature in the pipeline ?

Regards
Dimeji

**Comment by olafayomi** [comment]
@dvolodin7 Hi Dmitry, 
How complex is it to introduce this feature and how can I help to get it out. I don't know much about how to code in Rust but I could help with the Python side of things, if it helps.

**Comment by dvolodin7** [comment]
Hi,
Thank you for your feedback. I need to perform some investigations and will be back soon.

**Comment by dvolodin7** [comment]
@olafayomi We have added Ping `src_addr` parameter in 2c54ef10384e06d6d0d5b4ce68e26c4b4b9899f2 and fa7298368ca9d76cab2019725950933cba518479. Can you take a look?

Except from documentation:

src_addr: Set source address for outgoing packets.  Depends upon address family. May be one of:
          
* None - detect source address automatically.
* str - containing source address for one address family.
* Iterable of strings, containing multiple addresses
              which to be distributed among the address families.
              First address for given address family will be used.

**Comment by olafayomi** [comment]
Hi Dmitry, 
I have just tested  the patch that added the ```src_addr``` parameter by specifying an IPv6 source address string and it works. I did not test for IPv4 or multiple addresses though.
Thank you very much for this change.

**Comment by dvolodin7** [comment]
I have tried on IPv4. Anyway, it's only a `bind()` call.
